eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8030

spring:
  application:
    name: colaboradores
  data:
    mongodb:
      authentication-database: admin
      host: mongo
      port: 27017
      username: root
      password: fiap-mba
      database: colaboradores
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      load-on-startup: 1
