version: '3.8'

services:
  eureka:
    image: "lincolncarvalho/eureka:${BUILD_TAG}"
    build:
      context: ./eureka
    ports:
      - 8761:8761
    networks:
      - microservice-network

  gateway:
    image: "lincolncarvalho/gateway:${BUILD_TAG}"
    build:
      context: ./gateway
    ports:
      - 8080:8080
    networks:
      - microservice-network

  cursos:
    image: "lincolncarvalho/cursos:${BUILD_TAG}"
    build:
      context: ./cursos
    ports:
      - 8020:8020
    networks:
      - microservice-network

  trilhas:
    image: "lincolncarvalho/trilhas:${BUILD_TAG}"
    build:
      context: ./trilhas
    ports:
      - 8010:8010
    networks:
      - microservice-network

  colaboradores:
    image: "lincolncarvalho/colaboradores:${BUILD_TAG}"
    build:
      context: ./colaboradores
    ports:
      - 8030:8030
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
