version: '3.8'

services:
  mongo:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    env_file:
      - ./config_files/.env_db_mongo
    networks:
      microservice-network-swarm:
        aliases:
          - mongo

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    env_file:
      - ./config_files/.env_db_admin
    networks:
      microservice-network-swarm:
        aliases:
          - mongo-express

  eureka:
    image: "lincolncarvalho/eureka:${SWARM_TAG}"
    deploy:
      replicas: 1
    ports:
      - "8761:8761"
    networks:
      microservice-network-swarm:
        aliases:
          - eureka

  gateway:
    image: "lincolncarvalho/gateway:${SWARM_TAG}"
    deploy:
      replicas: 1
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    networks:
      microservice-network-swarm:
        aliases:
          - gateway

  cursos:
    image: "lincolncarvalho/cursos:${SWARM_TAG}"
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - eureka
    ports:
      - "8020:8020"
    networks:
      microservice-network-swarm:
        aliases:
          - cursos

  trilhas:
    image: "lincolncarvalho/trilhas:${SWARM_TAG}"
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - eureka
      - cursos
    ports:
      - "8010:8010"
    networks:
      microservice-network-swarm:
        aliases:
          - trilhas

  colaboradores:
    image: "lincolncarvalho/colaboradores:${SWARM_TAG}"
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - eureka
      - cursos
      - trilhas
    ports:
      - "8030:8030"
    networks:
      microservice-network-swarm:
        aliases:
          - colaboradores

volumes:
  mongodb_data_volume:

networks:
  microservice-network-swarm:
    driver: overlay
    ipam: 
      config:
        - subnet: 192.168.50.0/24
