version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fiap-mba
    networks:
      - microservice-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: fiap-mba
      ME_CONFIG_MONGODB_URL: mongodb://root:fiap-mba@mongo:27017/
    networks:
      - microservice-network

  eureka:
    image: lincolncarvalho/eureka:1.0
    ports:
      - 8761:8761
    networks:
      - microservice-network

  gateway:
    image: lincolncarvalho/gateway:1.0
    depends_on:
      - eureka
    ports:
      - 8080:8080
    networks:
      - microservice-network

  cursos:
    image: lincolncarvalho/cursos:1.0
    depends_on:
      - mongo
      - eureka
    ports:
      - 8020:8020
    networks:
      - microservice-network

  trilhas:
    image: lincolncarvalho/trilhas:1.0
    depends_on:
      - mongo
      - eureka
      - cursos
    ports:
      - 8010:8010
    networks:
      - microservice-network

  colaboradores:
    image: lincolncarvalho/colaboradores:1.0
    depends_on:
      - mongo
      - eureka
      - cursos
      - trilhas
    ports:
      - 8030:8030
    networks:
      - microservice-network

volumes:
  mongodb_data_volume:

networks:
  microservice-network:
    driver: bridge
