version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db
    env_file:
      - ./config_files/.env_db_mongo
    networks:
      - microservice-network

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - ./config_files/.env_db_admin
    networks:
      - microservice-network

  eureka:
    image: "lincolncarvalho/eureka:${TAG}"
    ports:
      - 8761:8761
    networks:
      - microservice-network

  gateway:
    image: "lincolncarvalho/gateway:${TAG}"
    depends_on:
      - eureka
    ports:
      - 8080:8080
    networks:
      - microservice-network

  cursos:
    image: "lincolncarvalho/cursos:${TAG}"
    depends_on:
      - mongo
      - eureka
    ports:
      - 8020:8020
    networks:
      - microservice-network

  trilhas:
    image: "lincolncarvalho/trilhas:${TAG}"
    depends_on:
      - mongo
      - eureka
      - cursos
    ports:
      - 8010:8010
    networks:
      - microservice-network

  colaboradores:
    image: "lincolncarvalho/colaboradores:${TAG}"
    depends_on:
      - mongo
      - eureka
      - cursos
      - trilhas
    ports:
      - 8030:8030
    networks:
      - microservice-network

volumes:
  mongodb_data_volume:

networks:
  microservice-network:
    driver: bridge
