server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: trilhas
  data:
    mongodb:
      authentication-database: admin
      host: mongo
      port: 27017
      username: root
      password: fiap-mba
      database: trilhas
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
